# 스프링 관련설정
spring:
  application:
    name: mvc-svc2-user



# 서버설정
server:

  # 서비스 포트
  port: 8082

  # 톰켓 Access log
  tomcat:

    basedir: .                    #spring boot가 실행되는 디렉토리를 기본 디렉토리로 설정

    accesslog:
      enabled: true               #엑세스로그 사용여부
      directory: log/accesslog    #앞서 지정한 base디렉토리 아래 ./logs 디렉토리에 로그 디렉토리 설정
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      pattern: '%{yyyy-MM-dd HH:mm:ss.SSS}t %a %s %b %D %r "%{User-Agent}i" "%{Referer}i" '





# AP 로그설정
logging:

  charset:
    console: UTF-8
    file: UTF-8

  file:
    name: ./log/${spring.application.name}.log
    max-history: 30       # 해당일이 지나면 로그 자동삭제

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) --- [%-10.10thread] %cyan([%logger{0}:%line] %M)  : %marker %msg%n"
    file:    "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%-10.10thread] [%logger{0}:%line] %M : %marker %msg%n"

  level:
    root: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    log4jdbc.log4j2: INFO    # 운영할땐 ERROR로, SQL 확인이 필요할 땐 INFO





# log4jdbc SQL 로깅관련 설정
log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  drivers: oracle.jdbc.OracleDriver
  dump:
    sql:
      maxlinelength: 0
